---
- hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - envanswer.yml

  tasks:
  - name: Create Anti-affinity rules for controllers
    vmware_vm_vm_drs_rule:
      hostname: "{{ vcenter }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      cluster_name: "{{ cluster_name }}"
      drs_rule_name: "{{ vm_prefix }}-controller-rule"
      vms:
          - "{{ vm_prefix }}-controller0"
          - "{{ vm_prefix }}-controller1"
          - "{{ vm_prefix }}-controller2"
      affinity_rule: False
      enabled: true
      state: present
    delegate_to: localhost
